<a href="https://colab.research.google.com/github/simpykumarimandal/CLTV_DA/blob/main/practice_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
# takes more time for calculation so numpy is used formatric multiplication

In [4]:
zeros =np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones=np.ones((2,2))
print(ones)

[[1. 1.]
 [1. 1.]]


In [14]:
a=np.random.random(4)#print num between 0-1
print(a)
b=np.random.random((2,3))
print(b)

[0.2241756  0.55466843 0.46605066 0.28979798]
[[0.41616587 0.5560566  0.29013122]
 [0.58986526 0.67759437 0.29372665]]


In [8]:
full=np.full((2,2),7)
print(full)

[[7 7]
 [7 7]]


In [11]:
#np.arange(start,stop,step)
sequence =np.arange(0,11,2)
print(sequence)

[ 0  2  4  6  8 10]


Vector ,matrix,tensorflow
VECTOR-1D
MATRIX=2D
TENSOR-ND

In [18]:
VECTOR=([1,2,3])
print(VECTOR)

matrix=np.array([[1,2,3],[2,3,4]])
print(matrix)

tensor =np.array([[1,2],[2,3],[3,4],[4,3]])
print(tensor)

[1, 2, 3]
[[1 2 3]
 [2 3 4]]
[[1 2]
 [2 3]
 [3 4]
 [4 3]]


Array properties

In [20]:
arr=np.array([[1,2,3],
             [4,5,3]])

print("Shape:" ,arr.shape)
print("dimension:",arr.ndim)
print("size:" ,arr.size)
print("dtype", arr.dtype)



Shape: (2, 3)
dimension: 2
size: 6
dtype int64


array reshaping

In [24]:
arr=np.arange(12)#print from 0to11
print("original",arr)
reshaped=arr.reshape(3,4)
print("\n reshaped",reshaped)

flattened=reshaped.flatten()#give copied arrayview
print("\n flattened",flattened)

raveled=reshaped.ravel()#give original view instead of copy
print("\n raveled " ,raveled)

original [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshaped [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [27]:
#transpose
transpose=reshaped.T
print("transposed array" ,transpose)

transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


Numpy array operations


In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing",arr[2:7])
print("with step",arr[1:8:2])
print("negative index",arr[-1])

basic slicing [3 4 5 6 7]
with step [2 4 6 8]
negative index 10


In [4]:
arr_2d= np.array([[1,2,3],
 [4,5,6],
  [7,8,9]])
print("specific element", arr_2d[1,2])
print(arr_2d[1,2])#row 1 and column 2 (row_num,col_num)

specific element 6
6


SORTING

In [5]:
unsorted =np.array([3,1,4,1,5,9,2,6])
print("sorted array", np.sort(unsorted))

sorted array [1 1 2 3 4 5 6 9]


In [6]:
arr_2d_unsort=np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array",np.sort(arr_2d_unsort,axis=0))
print("sorted 2d array",np.sort(arr_2d_unsort,axis=1))
#difference between axis=1 and axis=1

sorted 2d array [[1 1]
 [2 2]
 [3 3]]
sorted 2d array [[1 3]
 [1 2]
 [2 3]]


filter


In [7]:
numbers =np.array([1,2,3,4,5,6,7,8,9,10])
even_number =numbers[numbers%2==0]
print("even numbers", even_number)

even numbers [ 2  4  6  8 10]


FILTER with mask

In [8]:
#this is only usable with numpy
mask=numbers >5
print("numbers greater than 5 ", numbers[mask])
#

numbers greater than 5  [ 6  7  8  9 10]


In [9]:
#Fancy indexing vs np.where--similar to sql where

indices =[0,2,4]
print(numbers[indices])

WHERE_RESULT=np.where(numbers >5)
print("NP where",numbers[WHERE_RESULT])
#

[1 3 5]
NP where [ 6  7  8  9 10]


In [11]:
condition_array =np.where(numbers > 5,numbers*4,numbers)
print(condition_array)
#meaning of this code
# if(numbers>5){
#     numbers*4
# }else{
#     numbers
# }

[ 1  2  3  4  5 24 28 32 36 40]


In [12]:
condition_array =np.where(numbers > 5,"true","false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


adding and remvoing data

In [13]:
arr1 =np.array([1,2,3])
arr2 =np.array([4,5,6])

combo=arr1+arr2
print(combo)
combined =np.concatenate((arr1,arr2))
print(combined)

[5 7 9]
[1 2 3 4 5 6]


Array compatabi
lity


In [14]:
#if arrays are of same size it will print true otherwise flse
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([6,7,8])

print("Compatibility shapes",a.shape==b.shape)

Compatibility shapes True


In [15]:
#Vertical stack -add row to array
original=np.array([[1,2],[3,4]])
new_row =np.array([[5,6]])
with_new_row=np.vstack((original,new_row))
print(original)
print(with_new_row)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


In [16]:
#horizontal stack adds colimnto array
new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print('with new column',with_new_col)

with new column [[1 2 7]
 [3 4 8]]


In [18]:
arr=np.array([1,2,3,4])
deleted=np.delete(arr,2)
print(deleted)

[1 2 4]


Advance operation with Business examples

In [19]:
#Data Structure : [restaurant_id,2021,2022,2023,2024]
sales_data=np.array([
    [1,100,200,300,400],#paradise biryani
    [2,200,300,400,500],#beijing bites
    [3,300,400,500,600],#piza hub
    [4,400,500,600,700],#burger point
    [5,500,600,700,800]#chai point
])
print("===Zomato sales analysis===")
